# Generated by Django 5.2.1 on 2025-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_course_semester_alter_faculty_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech')], default='B.Tech.', max_length=50),
            preserve_default=False,
        ),
    ]
